# Generated by Django 5.0.6 on 2024-06-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BasePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tite", models.CharField(max_length=20)),
                ("description", models.TextField(max_length=120)),
                ("rate", models.IntegerField()),
            ],
        ),
    ]
