# Generated by Django 5.0.6 on 2024-06-21 10:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("project_1", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="basepage",
            old_name="tite",
            new_name="title",
        ),
    ]
