# Generated by Django 5.0.7 on 2024-07-21 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_1", "0002_rename_tite_basepage_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimeModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=30)),
                ("image", models.ImageField(upload_to="")),
                ("year", models.IntegerField()),
                ("genre", models.CharField(max_length=20)),
                ("episodes", models.CharField(max_length=20)),
                ("description", models.TextField(max_length=200)),
            ],
        ),
    ]
