# Generated by Django 5.0.7 on 2024-07-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("project_1", "0003_animemodel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="animemodel",
            name="description",
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name="animemodel",
            name="genre",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="animemodel",
            name="title",
            field=models.CharField(max_length=50),
        ),
    ]
